<?= $this->partial('/admin/common/header.phtml', array('userdetail' => $this->userdetail)); ?>
<?= $this->partial('/admin/menu/left.phtml', array('menus' => $this->menus, 'controller' => $this->controller)); ?> 

<form id="form1" method="POST" action="<?php echo $this->url('productattribute/default', array('controller' => 'productattribute', 'action' => 'update')); ?>">
    <table border="1">
        <tbody>
            <tr>
                <td>Status</td>
                <td>
                    <input type="hidden" name="actiontype" id="actiontype" />
                    <select name="active">
                        <option value="1">Active</option>
                        <option value="0">In-active</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Name</td>
                <td>
                    <input type="text" name="name" />
                </td>
            </tr>
            <tr>
                <td>Description</td>
                <td>
                    <input type="text" name="description" />
                </td>
            </tr>
            <tr>
                <td>Attribute Type</td>
                <td>
                    <select name="type" id="type">
                        <option>...</option>
                        <?php foreach ($this->attributetype as $key => $value) { ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                </td>
                <td style="text-align: right">
                    <input type="button" value="Cancel" onclick="gotoListPage()"/>
                    <input type="button" value="Add" onclick="submitPage('add')"/>
                </td>
            </tr>
        </tbody>
    </table>
</form>



<script>
    function gotoListPage() {
        window.location = '<?php echo $this->url('productattribute/default', array('controller' => 'productattribute', 'action' => 'index')); ?>';
    }
    function validateForm() {
        if(document.getElementById('type').value==''){
            alert('Attribute type not selected');
            document.getElementById('type').focus();
            return false;
        }else{
            return true;
        }
    }
    function submitPage(action) {
        if (validateForm()==true) {
            document.getElementById('actiontype').value = action;
            document.getElementById('form1').submit();
        }

    }
</script>

<?= $this->partial('/admin/common/footer.phtml', array()); ?>