<?= $this->partial('/admin/common/header.phtml', array('userdetail' => $this->userdetail)); ?>
<?= $this->partial('/admin/menu/left.phtml', array('menus' => $this->menus, 'controller' => $this->controller)); ?> 
<div class="main">
<div class="wrapper">
<h2>Product Attribute Add</h2>
<form id="form1" method="POST" action="<?php echo $this->url('productattribute/default', array('controller' => 'productattribute', 'action' => 'update')); ?>">
    <table class="field-control" border="1">
        <tbody>
            <tr>
                <td>Status</td>
                <td>
                    <input type="hidden" name="actiontype" id="actiontype" />
                    <select name="active">
                        <option value="1">Active</option>
                        <option value="0">In-active</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Name *</td>
                <td>
                    <input type="text" name="name" id="name" />
                </td>
            </tr>
            <tr>
                <td>Description *</td>
                <td>
                    <input type="text" name="description" id="description"/>
                </td>
            </tr>
            <tr>
                <td>Attribute Type</td>
                <td>
                    <select name="type" id="type">
                        <option></option>
                        <?php foreach ($this->attributetype as $key => $value) { ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                </td>
                <td style="text-align: right">
                    <input type="button" value="Cancel" onclick="gotoListPage()"/>
                    <input type="button" value="Add" onclick="submitPage('add')"/>
                </td>
            </tr>
        </tbody>
    </table>
</form>
</div>
</div>


<script>
    function gotoListPage() {
        window.location = '<?php echo $this->url('productattribute/default', array('controller' => 'productattribute', 'action' => 'index')); ?>';
    }
    function validate() {
        var responsevalue = true;
        var obj = new Array();
        obj[obj.length] = ['req', document.getElementById("type"), 'Attribute type not selected'];
        obj[obj.length] = ['req', document.getElementById("name"), 'Please enter Name'];
        obj[obj.length] = ['req', document.getElementById("description"), 'Please enter description'];
        for (cnt = 0; cnt < obj.length; cnt++) {
            responsevalue = V2validateData(obj[cnt][0], obj[cnt][1], obj[cnt][2]);
            if (responsevalue == false) {
                obj[cnt][1].focus();
                return false;
            }
        }
    }
    function submitPage(action) {
        if (validate() == false)
            return;
        uniqueAttribute(action);
//        document.getElementById('actiontype').value = action;
//        document.getElementById('form1').submit();
    }
    function uniqueAttribute(action) {
        var name = (document.getElementById('name').value).trim();
        var reloadurl = '<?php echo $this->url('productattribute/default', array('controller' => 'productattribute', 'action' => 'uniqueattribute')); ?>';
        //        Element.hide(obj);
        new Ajax.Request(reloadurl, {
            method: 'post',
            parameters: encodeURI('name=' + name),
            onComplete: function (transport) {
                if(transport.responseText=='0'){
                    document.getElementById('actiontype').value = action;
                    document.getElementById('form1').submit();
                }else{
                    alert('Attribute name ['+document.getElementById("name").value + '] already exist');
                    document.getElementById("name").focus();
                }
            }
        });
    }
</script>

<?= $this->partial('/admin/common/footer.phtml', array()); ?>