<?= $this->partial('/admin/common/header.phtml', array('userdetail' => $this->userdetail)); ?>
<?= $this->partial('/admin/menu/left.phtml', array('menus' => $this->menus, 'controller' => $this->controller)); ?> 
<div class="main">
<div class="wrapper">
<h2>Product Attribute Edit</h2>
<form id="form1" method="POST" action="<?php echo $this->url('productattribute/default', array('controller' => 'productattribute', 'action' => 'update')); ?>">
    <table class="field-control" border="1">
        <tbody>
            <tr>
                <td>Status</td>
                <td>
                    <input type="hidden" name="id" value="<?= $this->productattributedetail['id'] ?>" />
                    <input type="hidden" name="actiontype" id="actiontype" />
                    <select name="active">
                        <option value="1" <?= ($this->productattributedetail['active'] == 1) ? "selected" : "" ?>>Active</option>
                        <option value="0" <?= ($this->productattributedetail['active'] == 0) ? "selected" : "" ?>>In-active</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Name</td>
                <td>
                    <?= $this->productattributedetail['name'] ?>
                </td>
            </tr>
            <tr>
                <td>Description *</td>
                <td>
                    <input type="text" id="description" name="description" value="<?= $this->productattributedetail['description'] ?>" />
                </td>
            </tr>
            <tr>
                <td>Attribute Type *</td>
                <td>
                    <select name="type" id="type">
                        <option></option>
                        <?php foreach ($this->attributetype as $key => $value) { ?>
                            <option value="<?= $key ?>" <?= ($this->productattributedetail['type'] == $key) ? "selected" : "" ?>><?= $value ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="button" value="Delete" onclick="submitPage('delete')"/>
                </td>
                <td style="text-align: right">
                    <input type="button" value="Cancel" onclick="gotoListPage()"/>
                    <input type="button" value="Update" onclick="submitPage('update')"/>
                </td>
            </tr>
        </tbody>
    </table>
</form>
</div>
</div>


<script>
    function gotoListPage() {
        window.location = '<?php echo $this->url('productattribute/default', array('controller' => 'productattribute', 'action' => 'index')); ?>';
    }
    function validate() {
        var responsevalue = true;
        var obj = new Array();
        obj[obj.length] = ['req', document.getElementById("type"), 'Attribute type not selected'];
//        obj[obj.length] = ['req', document.getElementById("name"), 'Please enter Name'];
        obj[obj.length] = ['req', document.getElementById("description"), 'Please enter description'];
        for (cnt = 0; cnt < obj.length; cnt++) {
            responsevalue = V2validateData(obj[cnt][0], obj[cnt][1], obj[cnt][2]);
            if (responsevalue == false) {
                obj[cnt][1].focus();
                return false;
            }
        }
    }
    function submitPage(action) {
        if (action == 'delete') {
            if (!confirm('Are you sure to delete this Attribute ?') == true) {
                return;
            }
            document.getElementById('actiontype').value = action;
            document.getElementById('form1').submit();
        }else{
            if(validate()==false)return;
            document.getElementById('actiontype').value = action;
            document.getElementById('form1').submit();
        }

    }
</script>

<?= $this->partial('/admin/common/footer.phtml', array()); ?>