<table class='data' cellspacing='0' border='1'>
    <tr class='headings'>
        <th>Name</th>
        <th>Description</th>
        <th>Type</th>
        <th>Status</th>
        <th>Show in [Product list] ?</th>
        <th>Action</th>
    </tr>
    <?php
    $temp = false;
    $returntxt = '';
    $displays = true;
    foreach ($this->productattributelist as $item) {
        $temp = true;
        $style = '';
        ?>
        <tr class='<?= ($displays) ? 'even pointer' : 'pointer' ?>' style='cursor:default;<?= $style ?>' title='#'>
            <td class=''><?= $item['name'] ?></td>
            <td class=''><?= $item['description'] ?></td>
            <td class=''><?= $this->attributetype[$item['type']] ?></td>
            <td class=''><?= ($item['active'] == 1) ? 'Active' : 'In-active' ?></td>
            <td class=''><?= ($item['admin_list'] == 1) ? 'Yes' : 'No' ?></td>
            <td class=''><a href="javascript:editProductattribute(<?= $item['id'] ?>)" >Edit</a></td>
        </tr>
        <?php $displays = ($displays) ? false : true;
    }
    ?>
    <?php if ($temp == false) { ?>
        <tr><td colspan='5'>No attribute found</td></tr>
<?php } ?>
</table>