<?= $this->partial('/admin/common/header.phtml', array('userdetail' => $this->userdetail)); ?>
<?= $this->partial('/admin/menu/left.phtml', array('menus' => $this->menus, 'controller' => $this->controller)); ?> 

<link rel="StyleSheet" href="<?php echo $this->serverUrl() . $this->basePath('dtree/dtree.css'); ?>" type="text/css" />
<script type="text/javascript" src="<?php echo $this->serverUrl() . $this->basePath('dtree/dtree.js'); ?>"></script>

<div class="main">
    <div class="wrapper">
        <h2>Manage Category</h2>
        <table class="white" border="">
            <tbody>
                <tr>
                    <td>
                        <p><a href="javascript: d.openAll();">open all</a> | <a href="javascript: d.closeAll();">close all</a></p>
                        <script type="text/javascript">
                            <!--
                            d = new dTree('d', '<?php echo $this->serverUrl() . $this->basePath('dtree'); ?>');
                            d.add(0, -1, 'Category Tree', '<?php echo $this->serverUrl() . $this->basePath() . '/category/category/edit?id=0' ?>');
                            <?php foreach ($this->categorytree as $eachrow) { 
                                if($this->parentcategoryid==$eachrow['id'] || $this->categorydetail['id']==$eachrow['id']){
                                    $eachrow['name'] = '<b>'.$eachrow['name'].'</b>';
                                }
                                ?>
                                d.add(<?= $eachrow['id'] ?>, <?= $eachrow['parent_id'] ?>, '<?= $eachrow['name'] ?>', '<?php echo $this->serverUrl() . $this->basePath() . '/category/category/edit?id=' . $eachrow['id'] ?>');
                            <?php } ?>
                            document.write(d);
                            //-->
                        </script>
                    </td>
                    <td>
                        <?php if ($this->categorydetail) { ?>
                            <?= $this->partial('/category/category/update.phtml', array('categorydetail' => $this->categorydetail)); ?>
                        <?php } else if ($this->parentcategoryid!='') { ?>
                            <?= $this->partial('/category/category/subcategory.phtml', array('parentcategoryid' => $this->parentcategoryid, 'parentcategoryname' => $this->parentcategoryname)); ?>
                        <?php } ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>


<?= $this->partial('/admin/common/footer.phtml', array()); ?>