<?= $this->partial('/admin/common/header.phtml', array('userdetail' => $this->userdetail)); ?>
<?= $this->partial('/admin/menu/left.phtml', array('menus' => $this->menus, 'controller' => $this->controller)); ?> 

<link rel="StyleSheet" href="<?php echo $this->serverUrl() . $this->basePath('dtree/dtree.css'); ?>" type="text/css" />
<script type="text/javascript" src="<?php echo $this->serverUrl() . $this->basePath('dtree/dtree.js'); ?>"></script>


<form id="form1" method="POST" action="<?php echo $this->url('product/default', array('controller' => 'product', 'action' => 'update')); ?>">
    <table border="1">
        <tbody>
            <tr>
                <td>Status</td>
                <td>
                    <input type="hidden" name="id" value="<?= $this->productdetail['id'] ?>" />
                    <input type="hidden" name="actiontype" id="actiontype" />
                    <select name="status">
                        <option value="1" <?= ($this->productdetail['status'] == 1) ? "selected" : "" ?>>Active</option>
                        <option value="0" <?= ($this->productdetail['status'] == 0) ? "selected" : "" ?>>In-active</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Name</td>
                <td>
                    <input type="text" name="name" value="<?= $this->productdetail['name'] ?>" />
                </td>
            </tr>
            <tr>
                <td>Description</td>
                <td>
                    <input type="text" name="description" value="<?= $this->productdetail['description'] ?>" />
                </td>
            </tr>
            <tr>
                <td>Short Description</td>
                <td>
                    <input type="text" name="short_description" value="<?= $this->productdetail['short_description'] ?>" />
                </td>
            </tr>
            <tr>
                <td>Price</td>
                <td>
                    <input type="text" name="price" value="<?= $this->productdetail['price'] ?>" />
                </td>
            </tr>
            <tr>
                <td>Inventory</td>
                <td>
                    <input type="text" name="inventory" value="<?= $this->productdetail['inventory'] ?>" />
                </td>
            </tr>
            <tr>
                <td>Category</td>
                <td>
                    <input type="text" name="category" value="<?= $this->productdetail['category'] ?>" />
                    <p><a href="javascript: d.openAll();">open all</a> | <a href="javascript: d.closeAll();">close all</a></p>
                    <script type="text/javascript">
                    <!--
                        d = new dTree('d', '<?php echo $this->serverUrl() . $this->basePath('dtree'); ?>');
                        d.add(0, -1, 'Root', '');
                        <?php 
                        $tree = explode(',', $this->productdetail['category']);
                        foreach($this->categorytree as $eachrow){ ?>
                            d.add(<?=$eachrow['id']?>, <?=$eachrow['parent_id']?>, '<?=$eachrow['name']?>','<?php echo $this->serverUrl().$this->basePath().'/category/category/edit?id='.$eachrow['id']?>');
                        <?php } ?>
                        document.write(d);
                        //-->
                    </script>
                </td>
            </tr>
            <tr>
                <td>Belonging Customer</td>
                <td>
                    <input type="text" name="customer_id" value="<?= $this->productdetail['customer_id'] ?>" />
                </td>
            </tr>
            
            <tr>
                <td>Approved</td>
                <td>
                    <select name="approved">
                        <option value="1" <?= ($this->productdetail['approved'] == 1) ? "selected" : "" ?>>Yes</option>
                        <option value="2" <?= ($this->productdetail['approved'] == 0) ? "selected" : "" ?>>No</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="button" value="Delete" onclick="submitPage('delete')"/>
                </td>
                <td style="text-align: right">
                    <input type="button" value="Cancel" onclick="gotoListPage()"/>
                    <input type="button" value="Update" onclick="submitPage('update')"/>
                </td>
            </tr>
        </tbody>
    </table>
</form>



<script>
    function gotoListPage(){
        window.location = '<?php echo $this->url('product/default', array('controller' => 'product', 'action' => 'index')); ?>';
    }
    function validateForm(){
        
    }
    function submitPage(action){
        if(action=='delete'){
            if(!confirm('Are you sure to delete this Product ?')==true){
                return;
            }
        }
        document.getElementById('actiontype').value = action;
        document.getElementById('form1').submit();
        
    }
</script>

<?= $this->partial('/admin/common/footer.phtml', array()); ?>