<?php
//    print_r('<pre>');
//    print_r($this->productlist);
?>
<table class='data' cellspacing='0' border='1'>
            <tr class='headings'>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Approved</th>
                <th>Status</th>
                <th>Image</th>
            <?php
                foreach($this->admin_attribute_list as $option_name){ ?>
                    <th><?=$option_name?></th>
                <?php }
            ?>
                <th>Action</th>
            </tr>
<?php
$temp = false;
$returntxt='';
$displays = true;
foreach ($this->productlist as $item) {
    $temp = true;
    $style = '';?>
        <tr class='<?= ($displays) ? 'even pointer' : 'pointer'?>' style='cursor:default;<?=$style?>' title='#'>
            <td class=''><?=$item['name']?></td>
            <td class=''><?=$item['description']?></td>
            <td class=''><?=$item['price']?></td>
            <td class=''><?= ($item['approved']==1)?'Yes':'No' ?></td>
            <td class=''><?= ($item['status']==1)?'Active':'In-active' ?></td>
            <td class=''>
                <?php foreach($item['imagepath'] as $eachimagepath){
                    if($eachimagepath[1]==1){?>
                    <img width="100" src="<?php echo $this->serverUrl() . $this->basePath($eachimagepath[0]); ?>">
                    <?php }}?>
            </td>
            <?php
                foreach($this->admin_attribute_list as $option_name){
                    foreach($item['attributedata'] as $eachoption){
                        if($eachoption['name'] == $option_name){
                            if($eachoption['attribute_type']=='String'){?>
                                <td class=''><?=$eachoption['att_string_val']?></td>
                            <?php }else if($eachoption['attribute_type']=='Integer'){?>
                                <td class=''><?=$eachoption['att_integer_val']?></td>
                            <?php }else if($eachoption['attribute_type']=='Yes / No'){?>
                                <td class=''><?=($eachoption['att_boolean_val'])?'Yes':'No' ?></td>
                            <?php }else if($eachoption['attribute_type']=='Decimal'){?>
                                <td class=''><?=$eachoption['att_decimal_val']?></td>
                            <?php }else if($eachoption['attribute_type']=='Date'){?>
                                <td class=''><?=date('d-m-Y', ($eachoption['att_date_val']))?></td>
                            <?php }else if($eachoption['attribute_type']=='Select'){
                                foreach ($eachoption['options'] as $eachattributeoption) {
                                    if($eachattributeoption['id']==$eachoption['att_select_val']){?>
                                        <td class=''><?=$eachattributeoption['title']?></td>
                                    <?php }
                                }
                                ?>
                            <?php }
                        }
                    }
                }
            ?>
            <td class=''><a href='javascript:editProduct(<?=$item['id']?>)'>Edit</a></td>
        </tr>
    <?php $displays = ($displays) ? false : true;
}?>
<?php if ($temp == false) {?>
    <tr><td colspan='3'>No Products found</td></tr>
<?php }?>
        </table>

<script>
    function editProduct(productid) {
        window.location = '<?php echo $this->url('product/default', array('controller' => 'product', 'action' => 'edit')); ?>?id='+productid;
    }
</script>