<?= $this->partial('/admin/common/header.phtml', array('userdetail' => $this->userdetail)); ?>
<?= $this->partial('/admin/menu/left.phtml', array('menus' => $this->menus, 'controller' => $this->controller)); ?> 
<form id="form1" method="POST" action="<?php echo $this->url('customer/default', array('controller' => 'customer', 'action' => 'update')); ?>">
    <table border="1">
        <tbody>
            <tr>
                <td>dealer_type</td>
                <td>
                    <input type="hidden" name="actiontype" id="actiontype" />
                    <select name="dealer_type">
                        <option value="1">Commercial</option>
                        <option value="2">Domestic</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>User Name *</td>
                <td>
                    <input type="text" name="username" id="username" />
                </td>
            </tr>
            <tr>
                <td>Password *</td>
                <td>
                    <input type="password" name="password" id="password" />
                </td>
            </tr>
            <tr>
                <td>Re-enter Password</td>
                <td>
                    <input type="password" id="re-password" />
                </td>
            </tr>
            <tr>
                <td>Position in Company</td>
                <td>
                    <input type="text" name="position_in_company" />
                </td>
            </tr>
            <tr>
                <td>Telephone no.</td>
                <td>
                    <input type="text" name="telephone" />
                </td>
            </tr>
            <tr>
                <td>Mobile no.</td>
                <td>
                    <input type="text" name="mobile"/>
                </td>
            </tr>
            <tr>
                <td>Name</td>
                <td>
                    <input type="text" name="name" />
                </td>
            </tr>
            <tr>
                <td>Email *</td>
                <td>
                    <input type="text" name="email" id="email"/>
                </td>
            </tr>
            <tr>
                <td>Company Name</td>
                <td>
                    <input type="text" name="company_name" />
                </td>
            </tr>
            <tr>
                <td>Website</td>
                <td>
                    <input type="text" name="website" />
                </td>
            </tr>
            <tr>
                <td>Status</td>
                <td>
                    <select name="state">
                        <option value="1">Enable</option>
                        <option value="2">Disable</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                </td>
                <td style="text-align: right">
                    <input type="button" value="Cancel" onclick="gotoListPage()"/>
                    <input type="button" value="Save" onclick="submitPage('add')"/>
                </td>
            </tr>
        </tbody>
    </table>
</form>



<script>
    function gotoListPage() {
        window.location = '<?php echo $this->url('customer/default', array('controller' => 'customer', 'action' => 'index')); ?>';
    }
    function validate() {
        var responsevalue = true;
        var obj = new Array();
        obj[obj.length] = ['req', document.getElementById("username"), 'Please enter Username'];
        obj[obj.length] = ['req', document.getElementById("password"), 'Please enter your password'];
        obj[obj.length] = ['req', document.getElementById("email"), 'Please enter email'];
        obj[obj.length] = ['email', document.getElementById("email"), 'Enter a valid Email address'];
        for (cnt = 0; cnt < obj.length; cnt++) {
            responsevalue = V2validateData(obj[cnt][0], obj[cnt][1], obj[cnt][2]);
            if (responsevalue == false) {
                obj[cnt][1].focus();
                return false;
            }
        }
        if(document.getElementById('password').value!=document.getElementById('re-password').value){
            alert('Password do not match');
            document.getElementById('password').focus();
            return false;
        }
        return false;
    }
    function submitPage(action) {
        if(validate()==false)return;
        document.getElementById('actiontype').value = action;
        document.getElementById('form1').submit();
    }
</script>

<?= $this->partial('/admin/common/footer.phtml', array()); ?>