<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title></title>
        <link rel="stylesheet" href="<?php echo $this->serverUrl().$this->basePath('css/styles.css'); ?>">
    </head>
    <body>
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('admin/default', array('controller' => 'index', 'action' => 'login')));
        $form->prepare();
        //echo $this->form()->openTag($form);
        //echo $this->formRow($form->get('usr_name'));
        //echo $this->formRow($form->get('usr_password'));
        //echo $this->formRow($form->get('rememberme'));
        //echo $this->formSubmit($form->get('submit'));
        //echo $this->form()->closeTag();
        ?>
        <section class="container">
            <div class="login">
                <h1 class="logo">Showroom Auction</h1>
                <div class="loginform">
                    <?php echo $this->form()->openTag($form); ?>
                    <ul>
                        <?php if($this->messages){?>
                        <li><span class="msg"><?php echo $this->escapeHtml($this->messages); ?></span></li>
                        <?php }?>
                        <li>
                            <label>Username</label>
                            <input type="text" name="usr_name" value="">
                        </li>
                        <li>
                            <label>Password</label>
                            <input type="password" name="usr_password" value="">
                        </li>
                        <li class="submit"><?php echo $this->formSubmit($form->get('submit')); ?></li>
                    </ul>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>
        </section>
    </body>
</html>